# spelling.yml is disabled per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
name: Spell checking

on:
  push:
    branches:
      - main
  pull_request:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - name: checkout-merge
        if: contains(github.event_name, 'pull_request')
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: checkout
        if: ${{ github.event_name == 'push' || contains(github.event.comment.body, '@check-spelling-bot apply') }}
        uses: actions/checkout@v4

      - uses: check-spelling/check-spelling@v0.0.22
        id: spelling
        if: ${{ github.event_name != 'issue_comment' || contains(github.event.comment.body, '@check-spelling-bot apply') }}
        with:
          experimental_apply_changes_via_bot: 1
          extra_dictionaries:
            cspell:cpp/c
